export const SET_IMAGES = 'SET_IMAGES'
export const SEARCH_IMAGES_START = 'SEARCH_IMAGES_START'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'

export const SET_PEXELS = 'SET_PEXELS'
export const DELETE_PEXELS = 'DELETE_PEXELS'
export const DELETE_PEXELS_START = 'DELETE_PEXELS_START'

export const UPLOAD_PEXEL_FAIL = 'UPLOAD_PEXEL_FAIL'
export const UPLOAD_PEXEL_START = 'UPLOAD_PEXEL_START'
export const UPLOAD_PEXEL_END = 'UPLOAD_PEXEL_END'
